### ISSUE TITLE
ConfigsPanel won't run setNewName() on edit

### ISSUE THREAD

**Issue by uksamc** [SpeakEasy-tools/SpeakEasy#51]
The TextField that contains the config name runs `setNewName(e.target.value)` on change, but only on change. If name isn't altered on edit (that is, name is just kept the same), `newName` is never updated from `null` and therefore `UpdateConfig` won't execute.

Need to setNewName to c.name upon "edit", to `e.target.value` on TextField change ?

**Comment by JerameyATyler** [comment]
Is this still an issue? I just tested this locally and it appears to be working.
